---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cluster-autoscaler-pullsecretmanager
  namespace: cluster-autoscaler-namespace
spec:
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.refreshInterval }}
  target:
    name: k8spullsecret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .Values.dockerhash }}"
  data:
    - secretKey: dockerhash
      remoteRef:
        key: imagepullsecret
        property: dockerhash
