---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cve-consumer-pullsecretmanager
  namespace: cve-consumer-namespace
spec:
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.refreshInterval }}
  target:
    name: registrypullsecret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .Values.dockerhash }}"
  data:
    - secretKey: dockerhash
      remoteRef:
        key: imagepullsecret
        property: dockerhash

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cve-consumer-secret-manager
  namespace: cve-consumer-namespace
spec:
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.refreshInterval }}
  target:
    name: app-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cve-consumer-secret
