rbac:
  serviceAccount:
    create: true
    name: cluster-autoscaler
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::637423520668:role/eksWorkerNodeRole

podAnnotations:
  sidecar.istio.io/inject: "false"

cloudProvider: aws
autoDiscovery:
  clusterName: eks-cluster
  namespace: cluster-autoscaler-namespace
awsRegion: us-east-1
