kafkaServer:
  - kafka-broker-0.kafka-broker-headless.kafka-namespace.svc.cluster.local:9092
  - kafka-broker-1.kafka-broker-headless.kafka-namespace.svc.cluster.local:9092
  - kafka-broker-2.kafka-broker-headless.kafka-namespace.svc.cluster.local:9092

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
