alertmanager:
  enabled: false

server:
  fullnameOverride: prometheus
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  persistentVolume:
    enabled: true
    size: 8Gi
    storageClass: "gp2"
    accessModes: ["ReadWriteOnce"]

  resources:
    requests:
      memory: "400Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  service:
    type: NodePort
    NodePort: 33000

extraScrapeConfigs: |
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: 
        - 'kafka-exporter-prometheus-kafka-exporter.monitoring.svc.cluster.local:9308'

  - job_name: 'kafka-exporter-jmx'
    static_configs:
      - targets: 
        - 'kafka-jmx-metrics.kafka-namespace.svc.cluster.local:5556'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: 
        - 'postgres-metrics.cve-consumer-namespace.svc.cluster.local:9187'
