apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
  namespace: llm-namespace
spec:
  secretName: tls-certificate # Name of the secret to store the issued TLS certificate and private key
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days
  commonName: grafana.eashanroy.me
  dnsNames:
  - grafana.eashanroy.me
  - llm.eashanroy.me
  - api.eashanroy.me
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
